name: Build Lemmy for ARMv7 (32-bit)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang pkg-config libssl-dev protobuf-compiler \
                              cmake gcc-arm-linux-gnueabihf postgresql-client
          cargo install --force --locked bindgen-cli

      - name: Install Rust and ARMv7 target
        run: |
          rustup update stable
          rustup default stable
          rustup target add armv7-unknown-linux-gnueabihf

      - name: Build Lemmy
        run: |
          export CC_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-gcc
          export CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc
          cargo build --release --target armv7-unknown-linux-gnueabihf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lemmy-armv7
          path: target/armv7-unknown-linux-gnueabihf/release/lemmy
          
