name: Build Lemmy for ARMv8 (AArch64)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang pkg-config libssl-dev protobuf-compiler \
                              cmake gcc-aarch64-linux-gnu postgresql-client
          cargo install --force --locked bindgen-cli

      - name: Install Rust and AArch64 target
        run: |
          rustup update stable
          rustup default stable
          rustup target add aarch64-unknown-linux-gnu

      - name: Build Lemmy
        run: |
          # Set linker and compiler for cross-compilation
          export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          cargo build --release --target aarch64-unknown-linux-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lemmy-aarch64
          path: target/aarch64-unknown-linux-gnu/release/lemmy
