name: Build Lemmy for ARMv8 32-bit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang pkg-config libssl-dev protobuf-compiler \
                              cmake gcc-aarch64-linux-gnu postgresql-client

      - name: Install Rust and ARMv8 32-bit target
        run: |
          rustup update stable
          rustup default stable
          rustup target add armv8-unknown-linux-gnueabihf

      - name: Build Lemmy
        run: |
          cargo build --release --target armv8-unknown-linux-gnueabihf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lemmy-armv8-unknown-linux-gnueabihf
          path: target/armv8-unknown-linux-gnueabihf/release/lemmy
          
