name: Build Lemmy for aarch64

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub provides ARM64 runners for ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pkg-config \
          libssl-dev \
          libpq-dev

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: aarch64-unknown-linux-gnu
        override: true

    - name: Build Lemmy (release mode)
      run: |
        cargo build --release --target aarch64-unknown-linux-gnu
        strip target/aarch64-unknown-linux-gnu/release/lemmy_server

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lemmy-aarch64-binaries
        path: |
          target/aarch64-unknown-linux-gnu/release/lemmy_server
          target/aarch64-unknown-linux-gnu/release/lemmy
